### PR TITLE
Add Runtastic download and convert to gpx method in README

### PR DESCRIPTION
**Pull request by yihong0618**
Add another sport app which can export tracks in README

### CODE REVIEW

**Comment by xsanda** [comment]
What format does Runtastic output? Is it possible to accept it directly?

There are also a few grammatical errors I’ll fix later today.

**Comment by yihong0618** [comment]
Thank you very much.
@xsanda  many json files are in different folders such as the picture below
image

**Comment by erik** [comment]
Closing this out as it's been quite a while now. Feel free to reopen if it's still relevant

**Comment by yihong0618** [comment]
@erik OK
and I made a project using mapbox support the gpx too, and support most running app
If you interest you can find here.
https://github.com/yihong0618/running_page

and thank you for your great repo.

**Pull request closed without merging**
